#!/bin/bash

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

echo "PUSH DETECTOR"
workspace=1145700648005039
branch=`git symbolic-ref --short -q HEAD`

echo "BRANCH NAME: $branch"

pid=$(python C:\\CGLUMBERJACK\\asana_utils.py -g pid)
echo "PROJECT ID: $pid"

result=$(curl -X GET "https://app.asana.com/api/1.0/projects/$pid" -H "Authorization: Bearer 0/60638fd908735ac8ed156242a9d39887")

echo "$result"
